### ISSUE TITLE
'autocannon is not a function' when upgrading to 0.16.2

### ISSUE THREAD

**Issue by mpfdavis** [mcollina/autocannon#104]
When updating autocannon from 0.16.1 to 0.16.2 all tests break with error:  "(0 , _autocannon2.default) is not a function" (using babel), Node 6.9.4.

**Comment by thekemkid** [comment]
Will do a quick fix now

**Comment by thekemkid** [comment]
Should be resolved with 0.16.3. Apologies for the inconvenience.
